### ISSUE TITLE
[Document] 구현사항에 완료 체크 기능 추가

### ISSUE THREAD

**Issue by yoouyeon** [42organization/42gg-onboarding-fe-01#1]
필수(혹은 선택)구현사항에 Todo 완료 체크 기능이 추가되면 좋을 것 같습니다.

**Comment by mike2ox** [comment]
요구사항 반영했습니다. ([참고](https://github.com/42organization/42gg-onboarding-fe-01/commit/25a5ca2bd09cd2a4bfc28a4ce5a53ad9eda49ef6))
